[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "streamlit>=1.47.0",
    "xlrd>=2.0.2",
    "yfinance>=0.2.65",
]
